version: "3.3"
services:
    
    #DATABASES
    db:
        image: mysql:5
        container_name: wordpress-mysql
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
        networks:
            - wpsite
    #setting up wordpress
    
    #phpmyadmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
        - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - wpsite
    
    #Wordpress
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
           - '8000:80'
        restart: always
        volumes: ['./:/var/www/html']
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        networks:
            - wpsite


networks:
    wpsite:

volumes:
    db_data:
